name: Flutter Build Release

on:
  push:
    branches: [main]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - name: Clone repository
        uses: actions/checkout@v4
      - run: flutter pub get
      - run: flutter clean
      - run: flutter test

  release-android:
    needs: [ test-app ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Keystore
        env:
          CI: true
          CM_ENCODED_CERT: ${{ secrets.SIGN_STORE_CERT }}
        run: |
          echo "CM_KEYSTORE_PATH=$(pwd)/keystore.jks" >> $GITHUB_ENV
          echo $CM_ENCODED_CERT > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      - run: flutter pub get
      - run: flutter clean
      - name: Build APK
        env:
          CM_KEYSTORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.SIGN_KEY }}
          CM_KEY_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
        run: flutter build apk
      - name: Build APP BUNDLE
        env:
          CM_KEYSTORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.SIGN_KEY }}
          CM_KEY_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
        run: flutter build appbundle
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: $(pwd)/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload APP BUNDLE
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: $(pwd)build/app/outputs/bundle/release/app-release.aab

  archive:
    needs: [ release-android ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Get App Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-release.apk
      - name: Download AAB
        uses: actions/download-artifact@v2
        with:
          name: app-release.aab
      - name: Archive
        env:
          APP_NAME: ${{ github.event.repository.name }}-release-v${{ steps.get_flutter_version.outputs.version_number }}.${{ steps.get_flutter_version.outputs.build_number }}-buildNum_${{ github.run_number }}
        run: |
          sudo apt-get update
          sudo apt-get install zip
          mv app-release.apk ${{env.APP_NAME}}.apk
          mv app-release.aab ${{env.APP_NAME}}.aab
          ls
          zip -r ${{env.APP_NAME}}.zip *
          echo "ARCHIVE HERE"