name: Flutter Build Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - name: Get App Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      - name: Test Flutter Version
        run: echo 'version_number:' ${{ steps.get_flutter_version.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_version.outputs.build_number }}
      - name: Get Branch Name
        id: branch
        run: echo "::set output name=branch::${GITHUB_REF##*/}"
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Decode Keystore
        env:
          CI: true
          CM_KEYSTORE_PATH: $(pwd)"/keystore.jks"
          CM_ENCODED_CERT:  ${{ secrets.SIGN_STORE_CERT }}
          CM_KEYSTORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.SIGN_KEY }}
          CM_KEY_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
        run: |
          echo $CM_ENCODED_CERT > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
          pwd
          ls -la
          cat keystore.jks
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --build-name "MyCustomAppName"
      - run: flutter build appbundle --build-name "MyCustomAppName"


