name: Flutter Build Release

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - name: Clone repository
        uses: actions/checkout@v4
      - run: flutter pub get
      - run: flutter clean
      - run: flutter test

  release-android:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Keystore
        env:
          CI: true
          CM_ENCODED_CERT: ${{ secrets.SIGN_STORE_CERT }}
        run: |
          echo "CM_KEYSTORE_PATH=$(pwd)/keystore.jks" >> $GITHUB_ENV
          echo $CM_ENCODED_CERT > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks
      - run: flutter pub get
      - run: flutter clean
      - name: Build APK
        env:
          CM_KEYSTORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.SIGN_KEY }}
          CM_KEY_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
        run: flutter build apk
      - name: Build APP BUNDLE
        env:
          CM_KEYSTORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
          CM_KEY_ALIAS: ${{ secrets.SIGN_KEY }}
          CM_KEY_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
        run: flutter build appbundle


  archive-android:
    needs: [ release-android ]
    runs-on: ubuntu-latest
    steps:
      - name: Archive
        run: echo "ARCHIVE HERE"